# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geradornf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emitente',
            name='im',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='emitente',
            name='pais',
            field=models.CharField(default='Brasil', max_length=200),
        ),
    ]
