# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geradornf', '0004_emitente_data_cadasttro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CFOP', models.IntegerField()),
                ('EAN', models.CharField(blank=True, max_length=50, null=True)),
                ('NCM', models.IntegerField()),
                ('descricao', models.CharField(max_length=300)),
                ('unidade', models.CharField(max_length=2)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=9)),
                ('data_cadasttro', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('descricao',),
                'db_table': 'produto',
            },
        ),
        migrations.CreateModel(
            name='Transportador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frete_por_conta', models.BooleanField(default=False)),
                ('cnpf_cnpj', models.CharField(max_length=14)),
                ('inscricao_estadual', models.CharField(max_length=20)),
                ('nome_razao', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=200)),
                ('cidade_codigo', models.IntegerField(blank=True, null=True)),
                ('cidade', models.CharField(max_length=200)),
                ('uf', models.CharField(max_length=2)),
                ('data_cadasttro', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('nome_razao',),
                'db_table': 'transportador',
            },
        ),
    ]
