# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 22:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geradornf', '0010_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinatario',
            name='cliente_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='geradornf.Cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emitente',
            name='cliente_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='geradornf.Cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='cliente_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='geradornf.Cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportador',
            name='cliente_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='geradornf.Cliente'),
            preserve_default=False,
        ),
    ]
