# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-13 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geradornf', '0012_auto_20160813_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinatario',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_destinatario', to='geradornf.Cliente'),
        ),
        migrations.AlterField(
            model_name='emitente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_emitente', to='geradornf.Cliente'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_produto', to='geradornf.Cliente'),
        ),
        migrations.AlterField(
            model_name='transportador',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_transportador', to='geradornf.Cliente'),
        ),
    ]
