# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-20 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geradornf', '0013_auto_20160813_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinatario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
